using System.Net;
using System.Text;
using VenueOS.Modules.Operations.Raffle;
using VenueOS.Modules.Operations;
using VenueOS.Venues;
using VenueOS.Core;

namespace VenueOS.Services.Tests;

public sealed class RaffleClientTests
{
    [Fact] public async Task Upsert_uses_standalone_camel_case_ticket_contract() { string? body = null; var handler = new Handler(async request => { Assert.Equal(HttpMethod.Post, request.Method); Assert.Equal("/api/raffles", request.RequestUri!.AbsolutePath); body = await request.Content!.ReadAsStringAsync(); return Json("{\"raffleId\":\"remote\",\"hostUrl\":\"https://x/host/remote/secret-host\",\"viewerUrl\":\"https://x/view/remote/secret-view\",\"winnerName\":null}"); }); var client = new VenueRaffleClient(new HttpClient(handler)); var raffle = new LocalRaffle("local", "Friday", DateTime.UnixEpoch, new(), [new("Ada", 2, 1)]); var result = await client.UpsertAsync(new("raffle.test"), raffle, default); Assert.True(result.Success); Assert.Contains("\"raffleId\":\"local\"", body); Assert.Contains("\"tickets\":[\"Ada\",\"Ada\",\"Ada\"]", body); Assert.Equal("remote", result.Value!.RaffleId); }
    [Fact] public async Task Fetch_escapes_token_and_deserializes_state() { Uri? uri = null; var handler = new Handler(request => { uri = request.RequestUri; return Task.FromResult(Json("{\"raffleId\":\"abc\",\"name\":\"Friday\",\"winnerName\":\"Ada\",\"tickets\":[\"Ada\"]}")); }); var result = await new VenueRaffleClient(new HttpClient(handler)).FetchAsync(new("https://raffle.test"), "abc", "host token?", default); Assert.True(result.Success); Assert.Contains("token=host%20token%3F", uri!.Query); Assert.Equal("Ada", result.Value!.WinnerName); }
    [Fact] public async Task Errors_cancellation_and_missing_url_do_not_expose_secrets() { var client = new VenueRaffleClient(new HttpClient(new Handler(_ => Task.FromResult(new HttpResponseMessage(HttpStatusCode.Forbidden) { ReasonPhrase = "Forbidden" })))); var raffle = new LocalRaffle("a", "A", DateTime.UtcNow, new(), []); var error = await client.UpsertAsync(new("https://x"), raffle, default); Assert.False(error.Success); Assert.DoesNotContain("secret", error.Error!, StringComparison.OrdinalIgnoreCase); using var cancel = new CancellationTokenSource(); cancel.Cancel(); var cancelled = await client.FetchAsync(new(""), "id", "secret", cancel.Token); Assert.False(cancelled.Success); Assert.DoesNotContain("secret", cancelled.Error!, StringComparison.OrdinalIgnoreCase); }
    [Fact] public void Local_raffle_strips_urls_from_diagnostic_copy() { var raffle = new LocalRaffle("a", "A", DateTime.UtcNow, new(), [], HostUrl: "https://x/secret", ViewerUrl: "https://x/secret"); Assert.Null(raffle.WithoutSecrets().HostUrl); Assert.Equal(0, raffle.TotalTickets); }
    [Fact] public async Task Venue_switch_cancels_inflight_raffle_request() { var handler = new Handler((_, token) => Task.Delay(Timeout.InfiniteTimeSpan, token).ContinueWith<HttpResponseMessage>(_ => throw new OperationCanceledException())); var profiles = new VenueProfileService(new InMemoryVenueStore(), new ModuleHost()); var first = profiles.Current; var second = profiles.Create("Second"); profiles.SaveModuleConfig(first.Id, "games.raffle", 1, new VenueRaffleSettings(new("https://x"), [])); var service = new VenueRaffleService(new VenueRaffleClient(new HttpClient(handler)), profiles); service.Load(first.Id); var request = service.UpsertAsync(new LocalRaffle("id", "name", DateTime.UtcNow, new(), [])); service.Load(second.Id); var result = await request; Assert.False(result.Success); }
    private static HttpResponseMessage Json(string value) => new(HttpStatusCode.OK) { Content = new StringContent(value, Encoding.UTF8, "application/json") };
    private sealed class Handler : HttpMessageHandler { private readonly Func<HttpRequestMessage, CancellationToken, Task<HttpResponseMessage>> action; public Handler(Func<HttpRequestMessage, Task<HttpResponseMessage>> action) : this((request, _) => action(request)) { } public Handler(Func<HttpRequestMessage, CancellationToken, Task<HttpResponseMessage>> action) => this.action = action; protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) => action(request, cancellationToken); }
}
